version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "micro-dp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ghgauhtemrz1"
s3_prefix = "micro-dp"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
